# Generated by Django 5.1.4 on 2024-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carroestoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquecarrofilipe',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='estoquecarrotoninho',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='estoquecarrofilipe',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoquecarrotoninho',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
