# Generated by Django 5.1.4 on 2025-01-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carroestoque', '0002_estoquecarrofilipe_valor_estoquecarrotoninho_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecarrotoninho',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
