# Generated by Django 5.1.4 on 2025-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carroestoque', '0003_alter_estoquecarrotoninho_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecarrofilipe',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='estoquecarrotoninho',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
