# Generated by Django 5.1.4 on 2025-01-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carroestoque', '0004_alter_estoquecarrofilipe_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquecarrofilipe',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='estoquecarrotoninho',
            options={'ordering': ['-id']},
        ),
    ]
