# Generated by Django 5.1.4 on 2024-12-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('acogue', models.CharField(max_length=200)),
                ('cpf_cpnj', models.CharField(blank=True, max_length=16, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nivel', models.CharField(choices=[('BOM', 'bom'), ('MEDIO', 'medio'), ('RUIM', 'ruim')], max_length=5)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
