# Generated by Django 5.1.4 on 2025-01-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0003_alter_inflow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-data_lancamento']},
        ),
    ]
