# Generated by Django 5.1.4 on 2024-12-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.tipo')),
            ],
        ),
    ]
