# Generated by Django 5.1.4 on 2024-12-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produto.tipo'),
        ),
    ]
