# Generated by Django 5.1.4 on 2024-12-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_alter_produto_tipo'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_material', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_de_adicao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendedor.vendedor')),
            ],
        ),
    ]
