# Generated by Django 5.1.4 on 2025-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venfilipe',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ventoninho',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
