# Generated by Django 5.1.4 on 2025-01-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_vendedores', '0003_alter_venfilipe_obs_alter_venloja_obs_and_more'),
        ('carroestoque', '0004_alter_estoquecarrofilipe_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventoninho',
            name='produto',
        ),
        migrations.AlterField(
            model_name='venfilipe',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carroestoque.estoquecarrofilipe'),
        ),
        migrations.DeleteModel(
            name='VenLoja',
        ),
        migrations.DeleteModel(
            name='VenToninho',
        ),
    ]
