# Generated by Django 5.1.4 on 2025-01-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_vendedores', '0004_remove_ventoninho_produto_alter_venfilipe_produto_and_more'),
        ('carroestoque', '0005_alter_estoquecarrofilipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenToninho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantidade', models.IntegerField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carroestoque.estoquecarrotoninho')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
