# Generated by Django 5.1.4 on 2025-01-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carroestoque', '0004_alter_estoquecarrofilipe_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenderFilipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_cliente', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pagamento', models.CharField(choices=[('Dinheiro', 'din'), ('Pix', 'pix'), ('Cartão', 'cart'), ('Cheque', 'chec'), ('Fiado', 'prazo')], max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carroestoque.estoquecarrofilipe')),
            ],
        ),
    ]
