# Generated by Django 5.1.4 on 2024-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('salario_fixo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
