# Generated by Django 5.1.4 on 2025-01-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_vendedores', '0005_ventoninho'),
        ('venda_finalizada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InforVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=200)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('total_vendido', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_vendedores.venfilipe')),
            ],
        ),
        migrations.DeleteModel(
            name='VendaFinalizadaFilipe',
        ),
    ]
